### ISSUE TITLE
Update for Foliate version 3

### ISSUE THREAD

**Issue by archisman-panigrahi** [catppuccin/foliate#1]
Hi, it would be great if you update this theme for Foliate version 3.

Here is how the json file should be formatted. https://github.com/johnfactotum/foliate/blob/c17886d15613d09afa765156cd3f27db20141e74/docs/faq.md#how-to-use-custom-themes

**Comment by Ioulan** [comment]
The problem with v3 is that you need explicitly define the object `light` and `dark`(both of them, in order for the theme to work) Now the Catppuccin color scheme consist of 4 flavors and neither one of them have dark/light mode in pair.


Which is why I have combined mine into `latte`(light) and `mocha`(dark)`
Here's my configuration In case you've wanted it
source:  [ref commit](https://github.com/lime-desu/dootsfile/commit/545954e5c73db20be7b8912b2d30e15e9b46ba4a)
```json
{
  "label": "Catppuccin",
  "light": {
    "fg": "rgb(76, 79, 105)",
    "bg": "rgb(239, 241, 245)",
    "link": "rgb(220, 138, 120)"
  },
  "dark": {
    "fg": "rgb(205,214,244)",
    "bg": "rgb(30,30,46)",
    "link": "rgb(245, 224, 220)"
  }
}
```

**Comment by spookyintheam** [comment]
Hi, would any of you would be open to adding this change as a PR?

**Comment by Ioulan** [comment]
> Hi, would any of you would be open to adding this change as a PR?

Yeah sure, made a draft, what do you think? 

Though the flavors only use the same values for light/dark mode

**Comment by spookyintheam** [comment]
I see. So there is probably no other way to handle the light part in the dark themes? Because having light in something like mocha might confuse some users.

**Comment by Ioulan** [comment]
> I see. So there is probably no other way to handle the light part in the dark themes? Because having light in something like mocha might confuse some users.

So the best solution I can think of is by removing or making that light/dark mode value empty, if that certain flavour doesn't have any of that mode to prevent confusion

Now, if we remove the key value like this, the theme wouldn't display/appear on the app.
```diff
{
  "label": "Catppuccin Frappe",
-  "light": {
-    "fg": "",
-    "bg": "",
-    "link": ""
-  },
  "dark": {
    "fg": "rgb(198, 208, 245)",
    "bg": "rgb(48, 52, 70)",
    "link": "rgb(242, 213, 207)"
  }
}
```

**Comment by spookyintheam** [comment]
Okay so I currently do not have a Linux system handy right now. Can you confirm that this is working as intended? Give me a go ahead and then I'll merge this into the repo itself.

**Comment by Ioulan** [comment]
Can confirm it works,
Though take a look at this

Here's the screenshot using the flatpak version of foliate:


> [!NOTE]  
> I'm using gtk4 `ctp-moccha` colorscheme

**Mode:** `Dark`             |  **Mode:** `Light`
:-------------------------:|:-------------------------:
 ![Screenshot from 2024-01-15 16-14-21](https://github.com/catppuccin/foliate/assets/114978689/e8a86143-06cc-45b3-a88b-30abcd9ac068) |  ![Screenshot from 2024-01-15 16-14-04](https://github.com/catppuccin/foliate/assets/114978689/c2bddc2e-06f8-4375-bcef-41cde1a597e6)
|   **Latte** Dark  | **Latte** Light |
![Screenshot from 2024-01-15 16-20-45](https://github.com/catppuccin/foliate/assets/114978689/3e187ee1-6f9d-49b5-b407-c3b45119bf6e) |  ![Screenshot from 2024-01-15 16-20-36](https://github.com/catppuccin/foliate/assets/114978689/b111e358-35b1-4c84-944a-a79f9786baa7)
| **Mocha** Dark | **Mocha** Light |
| ![image](https://github.com/catppuccin/foliate/assets/114978689/034ab85a-9e66-47cb-b85e-0d83450a1c5f) |  ![image](https://github.com/catppuccin/foliate/assets/114978689/c60aa706-6b09-4c64-bea5-11096bcba50c) 

Maybe we should provide some key values instead of making that empty and use `latte` color scheme as light variant, the same goes for dark mode to use the `mocha`??

Or perhaps [combine it?](https://github.com/catppuccin/foliate/issues/1#issuecomment-1883019873)  into single theme without flavor?

**Comment by spookyintheam** [comment]
Checking out the latte image, I think it would be better if we just provide latte as the light variant in all themes. And provide mocha as the dark variant for latte. 
Because, the dark mode in latte seems...questionable haha. 
(Also sorry for the late responses, I've been swamped with work and IRL things)

**Comment by Ioulan** [comment]
> Checking out the latte image, I think it would be better if we just provide latte as the light variant in all themes. And provide mocha as the dark variant for latte. Because, the dark mode in latte seems...questionable haha. (Also sorry for the late responses, I've been swamped with work and IRL things)

Alright I've implemented that
They now have light/dark mode object key value.
![image](https://github.com/catppuccin/foliate/assets/114978689/95a3cf49-b12a-4d86-ba07-236367cd8af2)

**Comment by spookyintheam** [comment]
Alright, checked, LGTM!

**Comment by ConEstArthur** [comment]
> **Latte** Dark 	**Latte** Light
![Screenshot from 2024-01-15 16-20-36](https://private-user-images.githubusercontent.com/114978689/296694400-b111e358-35b1-4c84-944a-a79f9786baa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjQ4MzQsIm5iZiI6MTczMDIyNDUzNCwicGF0aCI6Ii8xMTQ5Nzg2ODkvMjk2Njk0NDAwLWIxMTFlMzU4LTM1YjEtNGM4NC05NDRhLWE3OWY5Nzg2YmFhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNzU1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDFiYzMwMDY0Y2MwMDVlZTM2Zjc0NTE0YzQ3ZDUzN2NmNzhmOTU2ZTQyYjdlYzA1NTZjNWM4NzA0NjBiZWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qbFtd3uGP2OVcNa7dD41YGGrHMYgNVI4LqMFpKwC4NE)

can you tell me name of the font used in this epub please?
